#!/bin/sh
echo useradd ircensus
useradd ircensus

echo mkdir /var/log/ircensus
mkdir /var/log/ircensus

echo touch ircensus /var/log/ircensus/ircensus.log
touch ircensus /var/log/ircensus/ircensus.log

echo chmod 644 ircensus /var/log/ircensus/ircensus.log
chmod 644 /var/log/ircensus/ircensus.log

echo chown -R ircensus /var/log/ircensus
chown -R ircensus /var/log/ircensus

echo chmod u+x /etc/init.d/ircensus
chmod u+x /etc/init.d/ircensus

echo chmod u+x /usr/share/ircensus/bin/ircensus
chmod u+x /usr/share/ircensus/bin/ircensus

echo ln -s /etc/init.d/ircensus /etc/rc0.d/K97ircensus
ln -s /etc/init.d/ircensus /etc/rc0.d/K97ircensus

echo ln -s /etc/init.d/ircensus /etc/rc3.d/S97ircensus
ln -s /etc/init.d/ircensus /etc/rc3.d/S97ircensus

echo ln -s /etc/init.d/ircensus /etc/rc6.d/K97ircensus
ln -s /etc/init.d/ircensus /etc/rc6.d/K97ircensus

exit 0